Document: qamqp
Title: Debian qamqp Manual
Author: <insert document author here>
Abstract: This manual describes what qamqp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qamqp/qamqp.sgml.gz

Format: postscript
Files: /usr/share/doc/qamqp/qamqp.ps.gz

Format: text
Files: /usr/share/doc/qamqp/qamqp.text.gz

Format: HTML
Index: /usr/share/doc/qamqp/html/index.html
Files: /usr/share/doc/qamqp/html/*.html
